compile: balanced_parenthsis.c balanced_parenthsis.h
	gcc -c balanced_parenthsis.c balanced_parenthsis.h
build: balanced_parenthsis.o
	gcc -o balanced_parenthsis.bin balanced_parenthsis.o
clean:
	rm -f *.o *~ *.bin *.log
